### ISSUE TITLE
Missing resources?

### ISSUE THREAD

**Issue by Lestat** [GTWCode/GTW-RPG#20]
Hi. I downloaded the source code of your gamemode because I was impressed with many things in your server Grand Theft Walrus. Especially the Peds walking and driving vehicles near the player.

Yet when I "install" it, I can't find the peds resource anywhere, only the train appears, no other ped nor vehicle.

Same thing for Groups and House system resources. I can't find them.

Are those (the most impressive resources) not added on purpose?

Thank you for your time.

**Comment by TheMoose-GTW** [comment]
That's right, those resources are available as open source but due to their license restrictions not a part of the open GTW-RPG project. Our servers are based on this game mode but the game mode is not bound to the servers in any way. Our goal for v3.0 is to include all these "missing" resources however, the work is in progress.

**Comment by Lestat** [comment]
It was, thank you very much.
